# GitHub Copilot configuration for autonomous issue resolution
# This file configures Copilot to automatically analyze and fix autonomy issues

rules:
  - name: "Auto-fix autonomyd daemon issues"
    description: "Automatically fix common autonomyd daemon issues"
    patterns:
      - "daemon_down"
      - "daemon_hung"
      - "crash_loop"
    actions:
      - create_pull_request
      - run_tests
      - update_documentation
    allowed_files:
      - "cmd/autonomyd/**/*.go"
      - "pkg/**/*.go"
      - "scripts/**/*"
      - "docs/**/*.md"
    priority: "high"
    auto_merge: false
    require_review: true

  - name: "Auto-fix system degradation issues"
    description: "Automatically fix system-level degradation issues"
    patterns:
      - "system_degraded"
      - "slow"
    actions:
      - create_pull_request
      - run_tests
      - update_documentation
    allowed_files:
      - "pkg/sysmgmt/**/*.go"
      - "pkg/performance/**/*.go"
      - "scripts/**/*"
      - "docs/**/*.md"
    priority: "medium"
    auto_merge: false
    require_review: true

  - name: "Auto-fix notification issues"
    description: "Automatically fix notification system issues"
    patterns:
      - "notification_failure"
      - "webhook_error"
    actions:
      - create_pull_request
      - run_tests
      - update_documentation
    allowed_files:
      - "pkg/notifications/**/*.go"
      - "docs/**/*.md"
    priority: "medium"
    auto_merge: false
    require_review: true

  - name: "Auto-fix configuration issues"
    description: "Automatically fix configuration-related issues"
    patterns:
      - "config_error"
      - "uci_error"
    actions:
      - create_pull_request
      - run_tests
      - update_documentation
    allowed_files:
      - "pkg/uci/**/*.go"
      - "configs/**/*"
      - "docs/**/*.md"
    priority: "low"
    auto_merge: false
    require_review: true

# Global settings
settings:
  # Enable autonomous issue analysis
  autonomous_analysis: true
  
  # Enable automatic PR creation
  auto_create_pr: true
  
  # Enable automatic testing
  auto_run_tests: true
  
  # Enable documentation updates
  auto_update_docs: true
  
  # Require human review before merging
  require_human_review: true
  
  # Maximum number of concurrent PRs
  max_concurrent_prs: 3
  
  # Cooldown period between PRs (minutes)
  pr_cooldown_minutes: 30
  
  # Maximum file size for analysis (KB)
  max_file_size_kb: 1000
  
  # Allowed file extensions
  allowed_extensions:
    - ".go"
    - ".md"
    - ".sh"
    - ".ps1"
    - ".yml"
    - ".yaml"
    - ".json"
    - ".conf"
    - ".example"

# Issue templates for Copilot
issue_templates:
  - name: "autonomy Alert"
    description: "Template for autonomy alert issues"
    labels:
      - "autonomy-alert"
      - "auto-generated"
    assignees:
      - "github-copilot"
    body: |
      ## autonomy Alert Report
      
      **Device**: {{ device_id }}
      **Firmware**: {{ fw }}
      **Severity**: {{ severity }}
      **Scenario**: {{ scenario }}
      **Timestamp**: {{ timestamp }}
      
      ### System Status
      - **Overlay Usage**: {{ overlay_pct }}%
      - **Available Memory**: {{ mem_avail_mb }} MB
      - **Load Average**: {{ load1 }}
      - **Ubus Status**: {{ ubus_ok }}
      
      ### Actions Taken
      {{ actions }}
      
      ### Description
      {{ note }}
      
      ### Diagnostic Information
      This issue was automatically created by the autonomy webhook receiver.
      - **Issue Key**: {{ issue_key }}
      - **Alert ID**: {{ alert_id }}
      - **Webhook Receiver**: {{ receiver_type }}
      
      ### Next Steps
      1. Review system logs for additional context
      2. Check if this is a known issue
      3. Verify system configuration
      4. Consider firmware update if applicable
      
      ---
      *This issue was automatically generated by the autonomy monitoring system.*

# Copilot behavior settings
behavior:
  # Analysis settings
  analysis:
    # Enable code analysis
    enabled: true
    
    # Analysis depth (shallow, medium, deep)
    depth: "medium"
    
    # Include test files in analysis
    include_tests: true
    
    # Include documentation in analysis
    include_docs: true
    
  # Fix generation settings
  fixes:
    # Enable automatic fix generation
    enabled: true
    
    # Fix confidence threshold (0-1)
    confidence_threshold: 0.8
    
    # Maximum fix complexity
    max_complexity: "medium"
    
    # Include tests with fixes
    include_tests: true
    
    # Include documentation updates
    include_docs: true
    
  # PR creation settings
  pull_requests:
    # Enable automatic PR creation
    enabled: true
    
    # PR title template
    title_template: "fix: {{ issue_title }}"
    
    # PR description template
    description_template: |
      ## Fix for {{ issue_title }}
      
      **Issue**: #{{ issue_number }}
      **Type**: {{ issue_type }}
      **Severity**: {{ severity }}
      
      ### Changes Made
      {{ changes_summary }}
      
      ### Testing
      - [ ] Unit tests pass
      - [ ] Integration tests pass
      - [ ] Manual testing completed
      
      ### Documentation
      - [ ] Code comments updated
      - [ ] README updated if needed
      - [ ] Changelog updated
      
      ---
      *This PR was automatically generated by GitHub Copilot.*

# Security settings
security:
  # Enable security analysis
  enabled: true
  
  # Security scan on PR creation
  scan_on_pr: true
  
  # Block PRs with security issues
  block_security_issues: true
  
  # Allowed security levels
  allowed_security_levels:
    - "low"
    - "medium"
  
  # Security tools to run
  security_tools:
    - "gosec"
    - "staticcheck"
    - "govulncheck"

# Monitoring and metrics
monitoring:
  # Enable Copilot metrics
  enabled: true
  
  # Metrics collection interval (minutes)
  collection_interval: 60
  
  # Metrics to collect
  metrics:
    - "issues_analyzed"
    - "fixes_generated"
    - "prs_created"
    - "fix_success_rate"
    - "average_fix_time"
    - "security_issues_found"
