run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - goimports

issues:
  exclude-rules:
    - path: _test\\.go
      linters:
        - gocyclo
        - dupl
        - goconst
    - path: pkg/testing/
      linters:
        - gosec
    - path: cmd/test-.*/
      linters:
        - gosec
        - gocyclo
    - linters:
        - unused
        - staticcheck
      text: "unused|deprecated|SA1019|U1000|ST1005"
