version: "1"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - goimports
  disable:
    - typecheck  # Disable typecheck due to Go 1.23 standard library issues

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G101  # Look for hardcoded credentials
      - G102  # Bind to all interfaces
      - G103  # Audit the use of unsafe block
      - G104  # Audit errors not checked
      - G106  # Audit the use of ssh.InsecureIgnoreHostKey
      - G107  # Url provided to HTTP request as taint input
      - G108  # Profiling endpoint is automatically exposed on /debug/pprof
      - G109  # Converting strconv.Atoi result to int32/int16
      - G110  # Potential DoS vulnerability via decompression bomb
      - G111  # Potential directory traversal
      - G112  # Potential slowloris attack
      - G113  # Usage of Rat.SetString in math/big with an overflow
      - G114  # Use of net/http serve function that has no support for setting timeouts
      - G201  # SQL query construction using format string
      - G202  # SQL query construction using string concatenation
      - G203  # Use of unescaped data in HTML templates
      - G204  # Audit use of command execution
      - G301  # Poor file permissions used when creating a directory
      - G302  # Poor file permissions used when creation file or using chmod
      - G303  # Creating tempfile using a predictable path
      - G304  # Potential file inclusion via variable
      - G305  # File path traversal when extracting zip archive
      - G306  # Poor file permissions used when writing to a file
      - G307  # Poor file permissions used when creating a file with os.Create
      - G401  # Detect the usage of DES, RC4, MD5 or SHA1
      - G402  # Look for bad TLS connection settings
      - G403  # Ensure minimum RSA key length of 2048 bits
      - G404  # Insecure random number source (rand)
      - G501  # Import blocklist: crypto/md5
      - G502  # Import blocklist: crypto/des
      - G503  # Import blocklist: crypto/rc4
      - G504  # Import blocklist: net/http/cgi
      - G505  # Import blocklist: crypto/sha1
      - G601  # Implicit memory aliasing in for loop

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: "1.23"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
    - path: pkg/testing/
      linters:
        - gosec
        - gocyclo
        - dupl
    - path: archive/
      linters:
        - gosec
        - gocyclo
        - dupl
        - goconst
        - misspell
        - errcheck
        - gosimple
  max-issues-per-linter: 0
  max-same-issues: 0
