version: "1"

run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - goimports
  disable:
    - typecheck  # Disable typecheck due to Go 1.23 standard library issues
