#!/bin/sh

# Add autonomy to services menu
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autonomy[-1]
	add ucitrack autonomy
	set ucitrack.@autonomy[-1].init=autonomy
	commit ucitrack
EOF

exit 0





