include $(TOPDIR)/rules.mk

APP_TITLE:=VuCI API Support for Autonomy APP
APP_DEPENDS:=+api-core
CLOSED_GPL_INSTALL:=y

# Enable Lua compilation
CONFIG_VUCI_COMPILE_LUA:=y

include ../api.mk

# call BuildPackage - OpenWrt buildroot signature
