#!/bin/sh /etc/rc.common

START=98
STOP=10

USE_PROCD=1

PROG=/usr/bin/starlink-tracker
CONFIG_FILE=/etc/config/starlink-tracking

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -c "$CONFIG_FILE"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    ubus call starlink_tracker reload
}
