name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'README.md', 'STATUS.md', 'ROADMAP.md', 'TODO.md', 'ARCHITECTURE.md' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'README.md', 'STATUS.md', 'ROADMAP.md', 'TODO.md', 'ARCHITECTURE.md' ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Install Jekyll
      run: |
        gem install jekyll bundler
        bundle install
        
    - name: Build documentation
      run: |
        cd docs
        jekyll build --destination ../_site
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation-build
        path: _site/
        
  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build-docs
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: documentation-build
        path: _site/
        
    - name: Deploy to GitHub Pages (Preview)
      uses: peaceiris/actions-gh-pages@v1
      with:
        github_token: ${{ secrets.AUTONOMY_GH_TOKEN }}
        publish_dir: ./_site
        destination_dir: preview/${{ github.event.number }}
        
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `📚 Documentation preview available at: https://${context.repo.owner}.github.io/${context.repo.repo}/preview/${context.issue.number}/`
          })
          
  deploy-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-docs
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: documentation-build
        path: _site/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v1
      with:
        github_token: ${{ secrets.AUTONOMY_GH_TOKEN }}
        publish_dir: ./_site
        
    - name: Notify deployment
      run: |
        echo "Documentation deployed to: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
