name: ShellCheck & Formatting

on:
  push:
    branches: [main, main-dev]
    paths:
      - 'scripts/**'
      - '*.sh'
      - '*.bash'
  pull_request:
    branches: [main, main-dev]
    paths:
      - 'scripts/**'
      - '*.sh'
      - '*.bash'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.AUTONOMY_GH_TOKEN }}

    - name: Install ShellCheck
      run: |
        echo "🔧 Installing ShellCheck..."
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Install shfmt
      run: |
        echo "🔧 Installing shfmt..."
        go install mvdan.cc/sh/v3/cmd/shfmt@latest

    - name: Find shell scripts
      run: |
        echo "🔍 Finding shell scripts..."
        find . -name "*.sh" -o -name "*.bash" | grep -v node_modules | grep -v .git > shell_scripts.txt
        echo "Found shell scripts:"
        cat shell_scripts.txt || echo "No shell scripts found"

    - name: Run ShellCheck on shell scripts
      run: |
        echo "🔍 Running ShellCheck..."
        if [ -s shell_scripts.txt ]; then
          while IFS= read -r script; do
            echo "Checking: $script"
            shellcheck "$script" || echo "ShellCheck found issues in $script"
          done < shell_scripts.txt
        else
          echo "No shell scripts found to check"
        fi

    - name: Verify shell script formatting (shfmt)
      run: |
        echo "🔍 Checking shell script formatting..."
        if [ -s shell_scripts.txt ]; then
          while IFS= read -r script; do
            echo "Checking formatting: $script"
            shfmt -d "$script" || echo "Formatting issues found in $script"
          done < shell_scripts.txt
        else
          echo "No shell scripts found to format check"
        fi

    - name: Check for shell script syntax
      run: |
        echo "🔍 Checking shell script syntax..."
        if [ -s shell_scripts.txt ]; then
          while IFS= read -r script; do
            echo "Checking syntax: $script"
            bash -n "$script" || echo "Syntax error in $script"
          done < shell_scripts.txt
        else
          echo "No shell scripts found for syntax check"
        fi

    - name: Create summary
      run: |
        echo "## 🐚 Shell Script Analysis Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -s shell_scripts.txt ]; then
          SCRIPT_COUNT=$(wc -l < shell_scripts.txt)
          echo "**Shell Scripts Analyzed**: $SCRIPT_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Scripts checked**:">> $GITHUB_STEP_SUMMARY
          while IFS= read -r script; do
            echo "- \`$script\`" >> $GITHUB_STEP_SUMMARY
          done < shell_scripts.txt
        else
          echo "**No shell scripts found**" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ Shell script analysis completed" >> $GITHUB_STEP_SUMMARY
