name: autonomy Webhook Receiver

on:
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      test_payload:
        description: 'Test payload (JSON)'
        required: false
        default: '{"device_id":"test","fw":"RUTX_R_00.07.17","severity":"critical","scenario":"daemon_down","note":"Test alert","overlay_pct":95,"mem_avail_mb":50,"load1":2.5,"ubus_ok":true,"actions":["restart"],"ts":1705776000}'
  
  # Webhook endpoint via repository dispatch
  repository_dispatch:
    types: [starwatch_alert]

env:
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SUPPORTED_VERSIONS: ${{ vars.SUPPORTED_VERSIONS || 'RUTX_R_00.07.17,RUTX_R_00.07.18,RUTX_R_00.08.00' }}
  MIN_SEVERITY: ${{ vars.MIN_SEVERITY || 'warn' }}
  COPILOT_ENABLED: ${{ vars.COPILOT_ENABLED || 'true' }}
  AUTO_ASSIGN: ${{ vars.AUTO_ASSIGN || 'true' }}

jobs:
  webhook-receiver:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Process webhook
      run: |
        # Get payload from workflow dispatch or repository dispatch
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          PAYLOAD='${{ github.event.inputs.test_payload }}'
          SIGNATURE=""
        else
          PAYLOAD='${{ toJSON(github.event.client_payload.payload) }}'
          SIGNATURE='${{ github.event.client_payload.signature }}'
        fi
        
        echo "Processing webhook payload..."
        node scripts/webhook-receiver.js "$PAYLOAD" "$SIGNATURE"
